### ISSUE TITLE
`npx xxscreeps start` returns error.

### ISSUE THREAD

**Issue by tianyma** [laverdet/xxscreeps#44]
Hi there, I install xxscreeps and run `npx xxscreeps start`, but an error occurred:
```
node:internal/process/esm_loader:74
    internalBinding('errors').triggerUncaughtException(
                              ^
/home/tianyma/xxscreeps/src/engine/db/storage/local/responder.ts:84
                                        request.reject(new Error(message.payload));
                                                       ^

Error: /home/tianyma/xxscreeps/src/engine/db/storage/local/blob.ts:185
                        throw new Error(`"${key}" does not exist`);
                              ^

Error: "terrain" does not exist
    at BlobStorage.req (/home/tianyma/xxscreeps/src/engine/db/storage/local/blob.ts:185:10)
    at null.<anonymous> (/home/tianyma/xxscreeps/src/engine/db/storage/local/responder.ts:154:16)
    at MessagePort.<anonymous> (/home/tianyma/xxscreeps/src/engine/db/storage/local/responder.ts:84:21)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
```

**Comment by laverdet** [comment]
Did you run `npx xxscreeps import` first?

**Comment by tianyma** [comment]
sorry, my mistake.
